# Generated by Django 6.0.3 on 2026-04-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_move_authuser_to_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='AccountEmailAddress',
        ),
        migrations.DeleteModel(
            name='AccountEmailConfirmation',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='SocialApp',
        ),
        migrations.DeleteModel(
            name='SocialToken',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
