# Generated by Django 6.0.3 on 2026-05-09 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        ('reports', '0002_report_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_widgets', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='chart_config',
            field=models.JSONField(blank=True, help_text='Last rendered ECharts config returned by the chart engine.', null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='chart_params',
            field=models.JSONField(blank=True, default=dict, help_text='Column names and options forwarded to the chart engine.'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('scatter', 'Scatter'), ('histogram', 'Histogram'), ('text', 'Text / Annotation'), ('report', 'Embedded Report')], max_length=20),
        ),
    ]
