from django.urls import path
from .views import DatalabViewSet

preview = DatalabViewSet.as_view({"get": "preview"})
inspect = DatalabViewSet.as_view({"get": "inspect"})
describe = DatalabViewSet.as_view({"get": "describe"})
fill_derived = DatalabViewSet.as_view({"post": "fill_derived"})
validate_formula = DatalabViewSet.as_view({"post": "validate_formula"})
fix_formula = DatalabViewSet.as_view({"post": "fix_formula"})
cast = DatalabViewSet.as_view({"post": "cast_columns"})
drop_duplicates = DatalabViewSet.as_view({"post": "drop_duplicates"})
update_cell = DatalabViewSet.as_view({"patch": "update_cell"})
rename_column = DatalabViewSet.as_view({"post": "rename_column"})
replace_values = DatalabViewSet.as_view({"post": "replace_values"})
drop_nulls = DatalabViewSet.as_view({"post": "drop_nulls"})
fill_nulls = DatalabViewSet.as_view({"post": "fill_nulls"})
detect_outliers = DatalabViewSet.as_view({"get": "detect_outliers"})
trim_outliers = DatalabViewSet.as_view({"post": "trim_outliers"})
impute_outliers = DatalabViewSet.as_view({"post": "impute_outliers"})
cap_outliers = DatalabViewSet.as_view({"post": "cap_outliers"})
transform_column = DatalabViewSet.as_view({"post": "transform_column"})
drop_columns = DatalabViewSet.as_view({"post": "drop_columns"})
add_column = DatalabViewSet.as_view({"post": "add_column"})
filter_rows = DatalabViewSet.as_view({"post": "filter_rows"})
clean_string = DatalabViewSet.as_view({"post": "clean_string"})
scale_columns = DatalabViewSet.as_view({"post": "scale_columns"})
extract_datetime = DatalabViewSet.as_view({"post": "extract_datetime"})
encode_columns = DatalabViewSet.as_view({"post": "encode_columns"})
normalize_column_names = DatalabViewSet.as_view({"post": "normalize_column_names"})
revert = DatalabViewSet.as_view({"post": "revert"})
suggest_cleaning = DatalabViewSet.as_view({"get": "suggest_cleaning"})

urlpatterns = [
    path("preview/<int:dataset_id>/", preview, name="datalab-preview"),
    path("inspect/<int:dataset_id>/", inspect, name="datalab-inspect"),
    path("describe/<int:dataset_id>/", describe, name="datalab-describe"),
    path("fill-derived/<int:dataset_id>/", fill_derived, name="datalab-fill-derived"),
    path("validate-formula/<int:dataset_id>/", validate_formula, name="datalab-validate-formula"),
    path("fix-formula/<int:dataset_id>/", fix_formula, name="datalab-fix-formula"),
    path("cast/<int:dataset_id>/", cast, name="datalab-cast"),
    path("drop-duplicates/<int:dataset_id>/", drop_duplicates, name="datalab-drop-duplicates"),
    path("rename-column/<int:dataset_id>/", rename_column, name="datalab-rename-column"),
    path("update-cell/<int:dataset_id>/", update_cell, name="datalab-update-cell"),
    path("replace-values/<int:dataset_id>/", replace_values, name="datalab-replace-values"),
    path("drop-nulls/<int:dataset_id>/", drop_nulls, name="datalab-drop-nulls"),
    path("fill-nulls/<int:dataset_id>/", fill_nulls, name="datalab-fill-nulls"),
    path("detect-outliers/<int:dataset_id>/", detect_outliers, name="datalab-detect-outliers"),
    path("trim-outliers/<int:dataset_id>/", trim_outliers, name="datalab-trim-outliers"),
    path("impute-outliers/<int:dataset_id>/", impute_outliers, name="datalab-impute-outliers"),
    path("cap-outliers/<int:dataset_id>/", cap_outliers, name="datalab-cap-outliers"),
    path("transform-column/<int:dataset_id>/", transform_column, name="datalab-transform-column"),
    path("drop-columns/<int:dataset_id>/", drop_columns, name="datalab-drop-columns"),
    path("add-column/<int:dataset_id>/", add_column, name="datalab-add-column"),
    path("filter-rows/<int:dataset_id>/", filter_rows, name="datalab-filter-rows"),
    path("clean-string/<int:dataset_id>/", clean_string, name="datalab-clean-string"),
    path("scale-columns/<int:dataset_id>/", scale_columns, name="datalab-scale-columns"),
    path("extract-datetime/<int:dataset_id>/", extract_datetime, name="datalab-extract-datetime"),
    path("encode-columns/<int:dataset_id>/", encode_columns, name="datalab-encode-columns"),
    path("normalize-column-names/<int:dataset_id>/", normalize_column_names, name="datalab-normalize-column-names"),
    path("revert/<int:dataset_id>/", revert, name="datalab-revert"),
    path("suggest-cleaning/<int:dataset_id>/", suggest_cleaning, name="datalab-suggest-cleaning"),
]
