# Generated by Django 6.0.3 on 2026-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_email_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='birthday',
            field=models.DateField(blank=True, help_text="User's date of birth.", null=True),
        ),
    ]
