# Generated by Django 6.0.3 on 2026-04-16 08:38

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_authuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='birthday',
            field=models.DateField(blank=True, help_text="User's date of birth.", null=True, validators=[apps.users.utils.validate_birthday_not_future]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(help_text='Primary email address for the user.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (auto-cropped to 1:1).", null=True, upload_to='profile_pics/'),
        ),
    ]
