"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ and read .env
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://127.0.0.1:8000", "http://localhost:8000"],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",  # Required for dj-rest-auth
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # Auth & Social Login
    "dj_rest_auth",
    "dj_rest_auth.registration",  # Required for registration endpoints
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django.contrib.sites",
    # Local apps
    "apps.users",
    "apps.core",
    "apps.datasets",
    "apps.datalab",
    "apps.goals",
    "apps.eda",
    "apps.visualization",
    "apps.reports",
    "apps.mlstudio",
    "apps.chat",
    "apps.dashboards",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

## Authentication Backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}

# Caching Configuration
# Development: In-memory cache (no Redis needed)
# Production: Redis cache
if DEBUG:
    # Use local memory cache for development (no Redis required)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
else:
    # Use Redis for production
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

DATAFRAME_CACHE_TTL = env.int("DATAFRAME_CACHE_TTL", default=7200)  # seconds, default 2 hours


# ===== CORS CONFIGURATION =====
# Cross-Origin Resource Sharing settings for API access
# Development: Allow all origins (for testing with localhost, Postman, etc.)
# Production: Restrict to specific frontend domains

if DEBUG:
    # Development: Allow all origins for convenience
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    # Production: Only allow specific origins
    CORS_ALLOWED_ORIGINS = env.list(
        "CORS_ALLOWED_ORIGINS",
        default=[
            "https://yourdomain.com",
            "https://www.yourdomain.com",
        ],
    )
    CORS_ALLOW_CREDENTIALS = True

# Methods allowed for CORS requests
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Headers allowed in CORS requests
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# REST Framework Config
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Lock down by default
    ),
    "URL_FORMAT_OVERRIDE": None,  # Free up ?format= for our export endpoint
    # Throttle rates — applied per-view, not globally.
    # Uses the configured CACHES backend (locmem in dev, Redis in prod).
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        "otp_resend":      "5/hour",   # ResendOTPView
        "otp_verify":      "10/hour",  # RegistrationOTPVerifyView
        "registration":    "10/hour",  # CustomRegisterView
        "login":           "20/hour",  # CustomLoginView (brute-force protection)
        "totp_verify":     "10/hour",  # TOTPVerifyLoginView (prevents TOTP brute-force)
        "totp_action":     "20/hour",  # TOTPSetupView / TOTPEnableView / TOTPDisableView
        "password_change": "5/hour",   # CustomPasswordChangeView
    },
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ===== EMAIL CONFIGURATION =====
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
if DEBUG and not EMAIL_HOST_USER:
    # No SMTP credentials set — print emails to console (link visible in terminal)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    # Use SMTP when credentials are provided (works in both dev and prod)
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
    EMAIL_PORT = env.int("EMAIL_PORT", default=587)
    EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@pyanalypt.com")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User-uploaded files like CSV, Excel, etc.)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "users.AuthUser"

# --- Allauth & Social Auth Configuration ---
SITE_ID = 1

# ===== ALLAUTH ACCOUNT SETTINGS =====
# Modern configuration for allauth v0.60+
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3

# Login methods: email + password only
ACCOUNT_LOGIN_METHODS = {"email"}

# Signup fields for allauth v65+: email/password only.
# Username is generated automatically in CustomAccountAdapter.
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
    "first_name",
    "last_name",
]

# Login/Logout
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = False

# Session Management
ACCOUNT_SESSION_REMEMBER = True

# ===== SOCIAL ACCOUNT SETTINGS =====
# Auto-signup with social accounts (no additional form needed)
SOCIALACCOUNT_AUTO_SIGNUP = True

# Query email from social provider
SOCIALACCOUNT_QUERY_EMAIL = True

# Automatically link social accounts if email matches
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Store extra data from provider (profile picture, name, etc.)
SOCIALACCOUNT_STORE_TOKENS = True

# JWT Configuration with dj-rest-auth
REST_AUTH = {
    "USE_JWT": True,
    # JWT_AUTH_HTTPONLY defaults to True which forces refresh="" in the response body.
    # Set to False so the refresh token is returned in the JSON body (SPA/mobile pattern).
    "JWT_AUTH_HTTPONLY": False,
    "USER_DETAILS_SERIALIZER": "apps.users.serializers.CustomUserDetailsSerializer",
    "REGISTER_SERIALIZER": "apps.users.serializers.InitialRegisterSerializer",
    # Require the current password when changing to a new one.
    "OLD_PASSWORD_FIELD_ENABLED": True,
}

# ===== SOCIAL ACCOUNT PROVIDERS =====
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
            "openid",  # Required for OpenID Connect
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "VERIFIED_EMAIL": True,  # Google emails are pre-verified
        # Fields to extract from Google OAuth response
        "FIELDS": [
            "id",
            "email",
            "name",
            "first_name",
            "last_name",
            "verified_email",
            "picture",  # Profile picture URL
            "locale",
        ],
        "EXCHANGE_TOKEN": True,
        "LOCALE_FUNC": lambda request: "en_US",
    }
}

GOOGLE_OAUTH_CALLBACK_URL = env(
    "GOOGLE_REDIRECT_URI", default="http://localhost:8000/api/v1/auth/google/callback/"
)

# Frontend URL where the user lands after clicking the verification link.
# {key} is replaced with the actual confirmation key.
# The frontend page should extract the key and POST it to /api/v1/auth/registration/verify-email/
ACCOUNT_EMAIL_CONFIRMATION_URL = env(
    "EMAIL_CONFIRMATION_URL",
    default="http://localhost:3000/verify-email/{key}",
)

# ===== CUSTOM ADAPTER FOR GOOGLE OAUTH DATA =====
# This will be used for regular (email/password) signup behavior
ACCOUNT_ADAPTER = "apps.users.adapters.CustomAccountAdapter"

# This will be used to populate AuthUser fields from Google metadata
SOCIALACCOUNT_ADAPTER = "apps.users.adapters.CustomSocialAccountAdapter"


# ===== OLLAMA AI SETTINGS =====
# Local LLM integration for data analysis
OLLAMA_API_URL = env("OLLAMA_API_URL", default="http://localhost:11434/api/generate")
OLLAMA_MODEL = env("OLLAMA_MODEL", default="qwen2.5:7b")
