# Generated by Django 6.0.3 on 2026-04-16 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0005_dataset_user_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalabIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MISSING_VALUE', 'Missing Value'), ('DUPLICATE', 'Duplicate Row'), ('OUTLIER', 'Outlier'), ('SEMANTIC_ERROR', 'Semantic Error'), ('DATA_TYPE', 'Data Type'), ('INCONSISTENT_FORMATTING', 'Inconsistent Formatting'), ('INVALID_VALUE', 'Invalid Value'), ('WHITESPACE_ISSUE', 'Whitespace Issue'), ('SPECIAL_CHAR_ENCODING', 'Special Characters & Encoding'), ('INCONSISTENT_NAMING', 'Inconsistent Naming'), ('LOGICAL_INCONSISTENCY', 'Logical Inconsistency')], max_length=50)),
                ('column_name', models.CharField(blank=True, default='', max_length=255)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('affected_rows', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_issues', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Datalab Issue',
                'verbose_name_plural': 'Datalab Issues',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WrangleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FILL_NA', 'Fill missing values'), ('DROP_ROWS', 'Drop rows'), ('DROP_DUPLICATES', 'Drop duplicates'), ('CLIP_OUTLIERS', 'Clip outliers'), ('REMOVE_OUTLIERS', 'Remove outliers'), ('CAST_COLUMN', 'Cast column type'), ('STANDARDIZE_FORMAT', 'Standardize format'), ('REPLACE_VALUES', 'Replace values'), ('STRIP_WHITESPACE', 'Strip whitespace'), ('FIX_ENCODING', 'Fix encoding'), ('STANDARDIZE_CASE', 'Standardize case'), ('RENAME_COLUMN', 'Rename column')], max_length=32)),
                ('column_name', models.CharField(blank=True, default='', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('rows_affected', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed'), ('REVERTED', 'Reverted')], default='PENDING', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrangle_ops', to='datasets.dataset')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrangle_ops', to='datalab.datalabissue')),
            ],
            options={
                'verbose_name': 'Wrangle Operation',
                'verbose_name_plural': 'Wrangle Operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
