# Generated by Django 6.0.3 on 2026-05-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlstudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='progress',
            field=models.IntegerField(default=0, help_text='Training progress (0-100).'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='target_column',
            field=models.CharField(blank=True, default='', help_text='Empty for clustering tasks.', max_length=200),
        ),
    ]
